/**
 * QuestionType.java
 */
package com.bdisys.survey.bean;

/**
 * @author Nimish
 *
 */
public enum QuestionType {
	MULTIPLECHOICE_SINGLEANSWER,MULTIPLECHOICE_MULTIPLEANSWER,DESCRIPTIVE,IMAGE,COMMENT,TEXTBOX,DATE_TIME,RATING_SCALE,MULTIPLE_TEXTBOX,MATRIX_TYPE_SINGLE_ANSWER_PER_ROW,MATRIX_TYPE_MULTIPLE_ANSWER_PER_ROW,NUMERICAL_TEXTBOX;
}
